
CREATE TEMPORARY TABLE Numbers (
    n INT
);

-- Generate numbers from 1 to 40 million
INSERT INTO Numbers (n)
SELECT
    ones.n + (tens.n * 10) + (hundreds.n * 100) + (thousands.n * 1000) + (ten_thousands.n * 10000) + (hundred_thousands.n * 100000) + (millions.n * 1000000) AS number
FROM
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones,
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens,
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds,
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) thousands,
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ten_thousands,
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundred_thousands,
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) millions
WHERE
    ones.n + (tens.n * 10) + (hundreds.n * 100) + (thousands.n * 1000) + (ten_thousands.n * 10000) + (hundred_thousands.n * 100000) + (millions.n * 1000000) <= 40000000;

-- Verify the numbers generated
SELECT COUNT(*) FROM Numbers;

-- Drop the temporary Numbers table if needed
-- DROP TEMPORARY TABLE Numbers;

-- Insert random data into the Users table
INSERT INTO Users (FirstName, LastName, DateOfBirth, Sex)
SELECT
    CONCAT('First', LPAD(FLOOR(RAND() * 100000), 5, '0')) AS FirstName,
    CONCAT('Last', LPAD(FLOOR(RAND() * 100000), 5, '0')) AS LastName,
    DATE_ADD('1970-01-01', INTERVAL FLOOR(RAND() * 36500) DAY) AS DateOfBirth,
    CASE WHEN RAND() < 0.5 THEN 'Male' ELSE 'Female' END AS Sex
FROM Numbers
LIMIT 40000000;
